### PR TITLE
feat: use newer adoptedStyleSheets API for programmatically changing/adding CSS

### PR DESCRIPTION
**Pull request by wridgeu**
Hey Marian,

once I saw the Tampermonkey version (nice) I was thinking about adjusting this, so here it goes :)

- https://web.dev/articles/constructable-stylesheets
- https://developer.mozilla.org/en-US/docs/Web/API/Document/adoptedStyleSheets

image
I would still understand if you'd be against this due to possible browser incompatibilities. 

Everything should work and stay the same. 

br :)

---

On another note: because this [here](https://github.com/marianfoo/sap-community-css/pull/1/files#diff-1404295c843a249920c49ba02f3e2445be854f054f7d4fd5f414f684be18807fR64-R72) was removed, I cannot differentiate granularly when the 'Answer' or 'Comment' button should be in the middle (question vs blog post). But, depending if that is wanted, I can add it back another way maybe. :)

### CODE REVIEW

**Comment by marianfoo** [comment]
> On another note: because this here was removed, I cannot differentiate granularly when the 'Answer' or 'Comment' button should be in the middle (question vs blog post). But, depending if that is wanted, I can add it back another way maybe. :)

Sorry, was not my intention, just the notification page was broken, so I tried to change it.
More than welcome to change it

**Comment by wridgeu** [comment]
> Sorry, was not my intention, just the notification page was broken, so I tried to change it.

Classic testing on prod, no other way to find it, haha. No worries, when I have time I'll try again 😁

**Comment by marianfoo** [comment]
btw: i saw that already because my trusted IDE hinted this, so thanks again for fixing this
image

**Comment by wridgeu** [comment]
"AI Fix In Chat", wild. Looks great :D

**Pull request merged**
